# Generated by Django 5.2.4 on 2025-07-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=255, unique=True)),
                ('user_name', models.CharField(max_length=255)),
                ('assessment_name', models.CharField(max_length=300)),
                ('assessment_type', models.CharField(max_length=300)),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('total_recordings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('ansId', models.AutoField(primary_key=True, serialize=False)),
                ('submission_id', models.CharField(max_length=255, null=True)),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('assessment_name', models.CharField(max_length=300, null=True)),
                ('assessmenttype', models.CharField(max_length=300, null=True)),
                ('question_id', models.IntegerField(null=True)),
                ('video', models.FileField(blank=True, upload_to='assessment_videos/')),
                ('que', models.CharField(max_length=300, null=True)),
                ('c_ans', models.CharField(max_length=300, null=True)),
                ('recorded_answer', models.CharField(max_length=300, null=True)),
                ('answer_accurecy', models.IntegerField(default=0, null=True)),
                ('confidence', models.IntegerField(default=0, null=True)),
                ('nervousness', models.IntegerField(default=0, null=True)),
                ('neutral', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
